import { createRoot } from "react-dom/client";
import { ProjectList } from "./scripts/ProjectList.js";

const projects = [
  {
    id: "icf-coaching-site",
    name: "ICF Coaching Landing",
    img: "/assets/images/projects/icf-coaching-site.png",
    imgSmall: "/assets/images/projects/icf-coaching-site-small.webp",
    tech: ["HTML5", "React.js", "Tailwind CSS", "Gatsby.js"],
    description: "This high-performance landing page was developed using Gatsby.js for a professional educational platform focusing on career coaching. The project demonstrates a masterful use of Tailwind CSS to create a clean, business-oriented interface with a clear content hierarchy. By leveraging static site generation, the platform ensures near-instant loading speeds and high performance, which are critical for visitor conversion. The page structure includes logically organized blocks for the program and speakers, providing an intuitive user journey toward registration.",
    link: "https://icf-coaching.netlify.app/",
    codeLink: "https://github.com/helen25sur/ICF-coaching-landing",
  },
    {
    id: "product-store-tailwind",
    name: "Product Store with Tailwind",
    img: "/assets/images/projects/product-store-tailwind.png",
    imgSmall: "/assets/images/projects/product-store-tailwind-small.webp",
    tech: ["HTML5", "React.js", "Tailwind CSS"],
    description: "A frontend-focused e-commerce application designed with a mobile-first approach. The project emphasizes clean component architecture. Styled exclusively with Tailwind CSS, it demonstrates the ability to create sophisticated, modern interfaces with high performance and intuitive user flows.",
    link: "https://helen25sur.github.io/product-store-tailwind/",
    codeLink: "https://github.com/helen25sur/product-store-tailwind",
  },
  {
    id: "bookshelf-vue-app",
    name: "SPA Bookshelf App with Vue.js",
    img: "/assets/images/projects/bookshelf-vue-app.png",
    imgSmall: "/assets/images/projects/bookshelf-vue-app-small.webp",
    tech:  ["HTML5", "CSS3", "JavaScript (ES6+)", "Vue.js", "REST API"],
    description: "This dynamic web application, built with Vue.js, is designed for the convenient search and organization of a personal library through seamless integration with external REST APIs. The project demonstrates proficiency in a modern component-based architecture, where every interface element—from book cards to navigation—is isolated and scalable. By implementing filtering and categorization features, users can effortlessly switch between bestseller lists and their own reading preferences. Special attention is paid to visual hierarchy and UX design, ensuring an aesthetic and intuitive presentation of extensive data sets. The responsive layout guarantees flawless performance across all devices, maintaining high speed and a smooth interface response.",
    link: "https://bookshelf-vue.netlify.app/",
    codeLink: "https://github.com/helen25sur/Bookshelf-app",
  },
  {
    id: "courses-app",
    name: "SPA Courses App",
    img: "/assets/images/projects/courses-app.png",
    imgSmall: "/assets/images/projects/courses-app-small.webp",
    tech:  ["HTML5", "CSS3", "JavaScript (ES6+)", "Vue.js", "REST API"],
    description: "A modern Single Page Application (SPA) designed to provide a seamless and intuitive course browsing experience. The application focuses on clean data visualization and efficient navigation through educational content. Developed a dynamic course catalog featuring server-side data fetching and efficient pagination for seamless navigation. Engineered a responsive Vue.js interface with interactive elements like skill tags and rating systems to enhance user engagement.",
    link: "https://helen25sur.github.io/tech-task-genesis-frontend-school/",
    codeLink: "https://github.com/helen25sur/tech-task-genesis-frontend-school",
  },
    {
    id: "onua-site",
    name: "Main Page National University 'Odesa Law Academy'",
    img: "/assets/images/projects/onua-site.png",
    imgSmall: "/assets/images/projects/onua-site-small.webp",
    tech: ["HTML5", "CSS3", "JavaScript(ES6+)"],
    description: "A professional frontend implementation of the university's official landing page. The project focuses on a clean, authoritative design with a highly organized information architecture. It features a responsive grid layout, interactive navigation, and optimized media content to ensure a seamless experience for students and visitors.",
    link: "https://onua.edu.ua/ua/",
  },
  {
    id: "weather-app",
    name: "Weather App",
    img: "/assets/images/projects/weather-app.png",
    imgSmall: "/assets/images/projects/weather-app-small.webp",
    tech: ["HTML5", "CSS3", "JavaScript(ES6+)"],
    description: "A sleek, interactive weather application providing real-time meteorological data. The project features a modern UI design, offering users a clear and visually appealing way to track current conditions and multi-day forecasts. Built with a focus on asynchronous API integration and dynamic DOM manipulation to ensure accurate, up-to-the-minute weather updates for any location.",
    link: "https://guileless-pastelito-470cc1.netlify.app/",
    codeLink: "https://github.com/helen25sur/weather-app",
  },
  {
    id: "calendar-app",
    name: "Interactive Glassmorphism Calendar",
    img: "/assets/images/projects/calendar-app.png",
    imgSmall: "/assets/images/projects/calendar-app-small.webp",
    tech: ["HTML5", "CSS3", "JavaScript(ES6+)"],
    description: "A visually elegant UI component featuring a modern 'glass' effect with soft transparency and background blurring. This project focuses on high-end CSS styling and precise layout management. It provides a clean, intuitive interface for date tracking, demonstrating a strong command of modern web design trends and aesthetic consistency.",
    link: "https://helen25sur.github.io/calendar-component/",
    codeLink: "https://github.com/helen25sur/calendar-component",
  },
   {
    id: "gsways-site",
    name: "GS Ways Multi-Pages Site",
    img: "/assets/images/projects/gsways-site.png",
    imgSmall: "/assets/images/projects/gsways-site-small.webp",
    tech:  ["HTML5", "CSS3", "JavaScript(ES6+)", "Eleventy", "BEM Methodology"],
    description: "Developed a comprehensive, multi-page web platform for Georgia Sea Ways, focusing on international ferry transportation for both cargo and passenger services. The project required a structured approach to present complex schedules, fleet information, and booking terms across multiple languages.",
    link: "https://gsways.com/eng/",
    codeLink: "https://github.com/helen25sur/gsw",
  },
  {
    id: "stardb-app",
    name: "SPA Star Wars DB",
    img: "/assets/images/projects/stardb-app.png",
    imgSmall: "/assets/images/projects/stardb-app-small.webp",
    tech:  ["HTML5", "CSS3", "React.js", "JavaScript (ES6+)", "REST API"],
    description: "A high-performance Single Page Application that allows users to explore detailed information about characters, planets, and starships from the Star Wars franchise. The project demonstrates the ability to handle complex asynchronous data flows and state management in a themed UI. Implemented efficient interaction with the SWAPI (Star Wars API) to fetch and display real-time data with integrated loading states and error handling. Built with React.js, utilizing reusable components for item lists and detail views to ensure code maintainability and scalability.",
    link: "https://helen25sur.github.io/star-db/",
    codeLink: "https://github.com/helen25sur/star-db",
  },
  //  {
  //   id: "candeleaf-site",
  //   name: "Online Shop 'Candeleaf' (in progress)",
  //   img: "/assets/images/projects/candeleaf-site.png",
  //   imgSmall: "/assets/images/projects/candeleaf-site-small.webp",
  //   tech: ["HTML5", "CSS3", "JavaScript (ES6+)", "Node.js & Express.js", "REST API"],
  //   description: "A clean, nature-inspired e-commerce application designed to provide a seamless shopping experience for organic products. The project focuses on minimalist aesthetics combined with robust backend functionality. Developed a full-cycle shopping experience, including a dynamic product catalog, detailed item views, and a functional shopping cart system. Powered by Node.js, the application handles data efficiently, ensuring smooth communication between the user interface and the server-side logic.", 
  //   link: "https://candleaf2.onrender.com/",
  //   codeLink: "https://github.com/helen25sur/online-shop-nodejs",
  // },
  {
    id: "task-manager-node",
    name: "Task Manager App",
    img: "/assets/images/projects/task-manager-node.png",
    imgSmall: "/assets/images/projects/task-manager-node-small.webp",
    tech: ["HTML5", "CSS3", "JavaScript (ES6+)", "Node.js & Express.js", "REST API"],
    description: "This Task Manager App is a robust full-stack application designed to streamline daily productivity through an intuitive and minimalist user interface. Built with Node.js and Express.js, the project features a custom REST API that handles all essential CRUD operations for efficient task management. The application provides a seamless user experience with real-time updates, allowing users to easily add, edit, and track the status of their to-do lists. It also includes a modern dark/light theme toggle and detailed task metadata, such as creation and modification timestamps. This project showcases a solid understanding of backend logic combined with a clean, responsive frontend design.", 
    link: "https://todo-nodejs-hf6g.onrender.com/",
    codeLink: "https://github.com/helen25sur/todo-nodejs",
  },
  {
    id: "product-page-plants",
    name: "Product Page 'Plants'",
    img: "/assets/images/projects/product-page-plants.png",
    imgSmall: "/assets/images/projects/product-page-plants-small.webp",
    tech:  ["HTML5", "CSS3", "JavaScript", "Responsive Design"],
    description: "This stylish landing page is designed to promote an indoor plant brand, focusing on a fresh, \"breathable\" aesthetic and clear visual hierarchy. The project features a well-structured layout that includes an integrated video showcase, benefit sections, and a clean navigation menu to guide users through the brand's story. Developed with a focus on responsive design, the landing ensures that the green, nature-inspired theme translates perfectly across all screen sizes. It effectively demonstrates the use of HTML5, CSS3, and JavaScript to create an engaging, modern web presence that balances multimedia content with readable typography.",
    link: "https://helen25sur.github.io/ProductPage-Plants/",
    codeLink: "https://github.com/helen25sur/ProductPage-Plants",
  },
  {
    id: "hofmann-site",
    name: "Landing 'Hofmann'",
    img: "/assets/images/projects/hofmann-site.png",
    imgSmall: "/assets/images/projects/hofmann-site-small.webp",
    tech:  ["HTML5", "CSS3", "BEM Methodology", "Responsive Design"],
    description: "A sleek, high-contrast landing page designed for a professional portfolio or creative agency, emphasizing clean typography and a monochrome aesthetic. The project showcases the power of pure CSS to create an engaging and elegant user experience. Implemented smooth entrance effects and hover transitions using CSS Keyframes to bring a sense of motion and life to the minimalist layout. Focused on a \"less is more\" approach, utilizing whitespace and balanced layouts to create a sophisticated and professional feel. Built with a mobile-first mindset, ensuring that all animated elements and layout structures adapt perfectly to any screen size.",
    link: "https://helen25sur.github.io/hofmann/",
    codeLink: "https://github.com/helen25sur/hofmann",
  },
  {
    id: "lakehouse-site",
    name: "Landing 'Lake House'",
    img: "/assets/images/projects/lakehouse-site.png",
    imgSmall: "/assets/images/projects/lakehouse-site-small.webp",
    tech:  ["HTML5", "CSS3", "Responsive Design"],
    description: "A visually stunning landing page designed to showcase a premium housing project integrated into a natural landscape. The site focuses on high-quality visual storytelling and a serene user experience to capture the essence of a peaceful forest retreat. Utilized large-scale, high-resolution imagery and a harmonious earth-tone color palette to create an immediate emotional connection with the user. Structured with a focus on clear information hierarchy, featuring dedicated blocks for location benefits, house features, and contact information. Developed with a responsive-first approach, ensuring that the tranquil aesthetic and layout integrity remain consistent across desktops, tablets, and mobile devices.",
    link: "https://helen25sur.github.io/lake-house-landing/",
    codeLink: "https://github.com/helen25sur/lake-house-landing",
  },
  {
    id: "magnatagallo-site",
    name: "Landing 'Magnata Gallo'",
    img: "/assets/images/projects/magnatagallo-site.png",
    imgSmall: "/assets/images/projects/magnatagallo-site-small.webp",
    tech: ["HTML5", "CSS3", "BEM Methodology", "Responsive Design"],
    description: "A sophisticated landing page for a high-end jewelry brand, focusing on visual elegance and a branded atmosphere. It features a soft pastel color palette and a clean, grid-based layout to ensure high-resolution imagery remains the central focus. Developed a clean, grid-based layout to showcase collections and special offers, ensuring that high-resolution imagery remains the central focus of the user experience. Crafted with a focus on cross-device compatibility, maintaining the delicate balance of typography and imagery across all screen resolutions ",
    link: "https://helen25sur.github.io/magnata-gallo/",
    codeLink: "https://github.com/helen25sur/magnata-gallo",
  },
];

const technologies = [
 "All", "HTML5", "CSS3", "JavaScript (ES6+)", "React.js", "Vue.js", "Node.js & Express.js", "REST API", "Tailwind CSS",
   ]

const container = document.getElementById("portfolio");
const root = createRoot(container);
root.render(<ProjectList projects={projects} technologies={technologies} />);